apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: alffino-python-hello
  namespace: alffino
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: alffino-python-hello
