apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: alffino-python-hello
  namespace: alffino
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: alffino-python-hello
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
